peer:
  id: peer0.org1.example.com
  networkId: arsiparis
  listenAddress: 0.0.0.0:7051
  address: peer0.org1.example.com:7051
  localMspId: Org1MSP
  mspConfigPath: /etc/hyperledger/fabric/organizations/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
  tls:
    enabled: true
    cert:
      file: /etc/hyperledger/fabric/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
    key:
      file: /etc/hyperledger/fabric/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
    rootcert:
      file: /etc/hyperledger/fabric/organizations/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt

logging:
  level: info

BCCSP:
  Default: SW
  SW:
    Hash: SHA2
    Security: 256
